zabbix: Autospec creation for update from version 6.2.3 to version 6.2.4
Aleksejs Sestakovs (14):
      ........S. [ZBX-21510] fixed compilation error
      ........S. [ZBX-17060] fixed unexpected interface connection mode change during
      ........S. [ZBXNEXT-7953] added VMware tags support for vSphere versions older than 7U2
      ........S. [ZBXNEXT-7953] fixed version check
      ........S. [ZBXNEXT-7953] fixed coding style
      .......PS. [ZBXNEXT-7953] fixed locks
      .......PS. [ZBXNEXT-7953] fixed unallocated memory access
      .......PS. [ZBXNEXT-7953] fixed coding style
      .......PS. [ZBXNEXT-7953] unset curl post option for delete request
      .......PS. [ZBXNEXT-7953] unset curl post option for delete request
      .......PS. [ZBXNEXT-7953] refactored zbx_vmware_service_update_tags()
      .......PS. [ZBXNEXT-7953] fixed authentication token parsing
      .......PS. [ZBXNEXT-7953] fixed buffer length
      .......PS. [ZBXNEXT-6401] fixed agent compilation for Windows

Alexander Vladishev (11):
      A.F.I..... [ZBXNEXT-7971] increased max length of the "URL (after login)" field
      A.F....... [ZBX-21097] fixed filtering by "Resource ID" and "Recordset ID" fields for "Audit log" page
      ..F....... [ZBX-21605] fixed possible PHP runtime errors in several modal popup dialogs
      .D........ [ZBXNEXT-826] updated ChangeLog
      .D........ [ZBXNEXT-826] updated ChangeLog
      .D........ [ZBXNEXT-826] updated ChangeLog
      .......... [ZBXNEXT-686] updated SonarCloud configuration files
      ..F....... [ZBX-21721] fixed non-translatable string
      .......... [ZBXNEXT-686] updated SonarCloud configuration files
      .......... [ZBXNEXT-686] updated SonarCloud configuration files
      .......... [ZBXNEXT-7122] removed incorrectly added ChangeLog entries

Andrejs Griščenko (2):
      ..F....... [ZBX-21544] fixed value of query field being truncated to the first "=" sign when pressing parse button
      ..F....... [ZBX-19512] fixed debug info block content refresh after changing table content in Monitoring -> Problems page

Andrejs Kozlovs (4):
      .......... [DEV-2169] added support of Timescale DB in integration tests
      .......... [DEV-2169] fixed Timescale test instability
      .......... [DEV-2169] fixed php syntax
      ........S. [ZBX-21706] fixed double precision update patch for TimescaleDb

Andrejs Verza (1):
      ..F....... [ZBX-21656] fixed clone buttons not working in Safari 16 on template editing form

Andrejs Zazuks (1):
      .......... [DEV-2239] added test cases for editable tags on host prototype

Andrey Tocko (10):
      .........T [ZBX-21421] fixed variable spelling
      .........T [ZBX-21421] fixed variable spelling in Kubernetes cluster state by HTTP template
      .........T [ZBX-20296] fixed swap trigger function for windows by Zabbix agent templates
      .........T [ZBX-20296] fixed swap trigger function for windows os and modules by Zabbix agent templates
      .........T [ZBX-21484] documentation update for templates SMART by Zabbix agent 2
      .........T [ZBX-21421] readme update for template ZYXEL MGS-3712F SNMP
      .........T [ZBX-20392] added close/ack/unack of events for OPSgenie media
      .........T [ZBX-21484] updated documentation for templates SMART by Zabbix agent 2
      .........T [ZBXNEXT-8018] added token authentication in Template GitLab by HTTP
      .........T [ZBXNEXT-8018] fixed Template GitLab by HTTP

Andris Zeila (2):
      .......PS. [ZBX-21725] fixed configuration cache leak when removing vault macros
      .D........ [ZBX-21725] added changelog entry

Armands Arseniuss Skolmeisters (5):
      ...G....S. [DEV-2260] removed redundant casts from C code
      ...G....S. [DEV-2260] readability improvement
      ...G....S. [DEV-2260] readability improvement
      ...G....S. [DEV-2260] removed redundant parentheses
      ...G....S. [DEV-2260] removed redundant type casts

Artjoms Rimdjonoks (1):
      ...G...... [ZBX-21466] fixed race condition in agent2 leading to permanently stuck mount reads

Continuous Integration (30):
      .......... [ZBX-1357] automatic update of translation strings
      .......... [ZBXNEXT-826] updated 5.0.29rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 6.0.10rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 6.2.4rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 5.0.29rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 6.0.10rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 6.2.4rc1 ChangeLog entries
      .......... [ZBX-1357] automatic update of translation strings
      .......... [ZBXNEXT-826] updated 5.0.29rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 6.0.10rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 6.2.4rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 5.0.29rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 6.0.10rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 6.2.4rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 5.0.29rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 6.0.10rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 6.2.4rc1 ChangeLog entries
      .......... [ZBX-1357] automatic update of translation strings
      .......... [ZBXNEXT-826] updated 5.0.29rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 6.0.10rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 6.2.4rc1 ChangeLog entries
      .......... [ZBX-1357] automatic update of translation strings
      .......... [ZBXNEXT-826] updated 5.0.29rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 6.0.10rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 6.2.4rc1 ChangeLog entries
      .......... [ZBXNEXT-826] updated 6.2.4rc1 ChangeLog entries
      .......... [ZBX-1357] automatic update of translation strings
      .......... [ZBXNEXT-826] automatic deployment of official Zabbix templates and media types
      .......... [ZBX-1357] automatic update of translation strings
      .......... [ZBX-1357] automatic update of translation strings

Dace Petra (3):
      ..F....... [ZBX-21000] fixed possibility to update host interface on items and item prototypes
      ..F....... [ZBX-21532] fixed missing inherited tags for templated triggers in edit form, tag tab
      ..F....... [ZBX-21708] fixed PHP TypeError when opening non-existing dashboard

Denis Rasihov (9):
      .........T [ZBX-21580] optimized HPE MSA 2060 Storage by HTTP template to spread the load across preprocessing workers
      .........T [ZBX-21579] optimized HPE MSA 2040 Storage by HTTP template to spread the load across preprocessing workers
      .........T [ZBX-21579] updated item keys and descriptions
      .........T [ZBX-21580] updated item keys and descriptions
      .........T [ZBX-21579] updated missed descriptions
      .........T [ZBX-21580] updated missed descriptions
      .........T [ZBX-21579] updated errors item key
      .........T [ZBX-21580] updated errors item key
      .........T [ZBX-21673] fixed read operations per second preprocessing in Ceph by Zabbix agent 2 template

Dmitrijs Goloscapovs (5):
      ...G...... [ZBX-21456] fixed net.tcp.socket.count and net.udp.socket.count problem on Zabbix agent 2 when IPv6 is disabled
      .......... [DEV-2292] fixed possible kill during forking in HA int tests
      .......PS. [ZBX-21724] fixed updating of active availability status when active proxy is used
      .......PS. [ZBX-21724] fixed conflict
      ..F.....S. [ZBXNEXT-7122] added checking for compression used in history or trends tables, and warnings if housekeeper overrides aren't enabled accordingly

Eriks Sneiders (1):
      .......... [ZBX-21388] set loaded plugins to capacity 1, updated plugin support to dev ver, fixed error handle for loaded plugin connection

Evgenii Gordymov (6):
      .........T [ZBX-21478] fixed value macro in "MongoDB cluster by Zabbix agent 2" template
      .......... [ZBX-21478] updated README file
      .........T [ZBX-21478] Revert value macro in "MongoDB cluster by Zabbix agent 2" template
      .........T [ZBX-21672] fixed event source in mediatypes
      .........T [ZBX-21672] fixed event source in mediatypes
      .........T [ZBX-21693] fixed repeated lines in templates

Gregory Chalenko (1):
      ..F....... [ZBX-21510] fixed error messages for failed connection to server

Janis Freibergs (1):
      ..F....... [ZBX-17300] fixed handling of context menu in Map builder

Jurijs Klopovskis (1):
      .......... [ZBXNEXT-826] updated to plugin support library version 1.1

Juris Lambda (2):
      ...G...PS. [ZBX-20864] fixed format specifier definitions on AIX
      ...G...... [ZBX-21610] fixed problem with sysctl() kern.proc.args API bug on FreeBSD <= 8.2

Katerina Kuzmina (2):
      ..F....... [ZBX-21682] removed unnecessary horizontal separator from Host interface
      ..F....... [ZBX-21606] fixed Allowed hosts field in HTTP agent item

Kirils Seve (2):
      .......... [DEV-2257] added new Selenium test cases for 'item value' widget with threshold settings
      .......... [DEV-2257] Selenium tests, removed tests that are not related to release/6.2

Konstantins Prutkovs (10):
      ........S. [ZBX-21510] NodeAddress now uses ListenIP and ListenPort if not specified
      ........S. [ZBX-21510] added check for 0.0.0.0 and changelog
      ........S. [ZBX-21510] fixed missing include
      ........S. [ZBX-21510] code style fixes
      ........S. [ZBX-21009] fixed double escaping in trigger function upon host autoregistration
      ...G...PS. [DEV-2261] updated GPL url for zabbix executables
      ........S. [ZBX-21510] changed NodeAddress configuration description to be more descriptive
      ...G...... [DEV-2207] added logging to agent2 before C calls
      ..F....... [ZBX-21510] changed frontend error message
      ..F....... [ZBX-21510] updated frontend tests to use new error messages

Kristaps Naglis (2):
      .........T [ZBXNEXT-8035] added override for file system discovery trigger in f5 template
      .........T [ZBXNEXT-8035] fixed punctuation and grammar for user macro

Larisa Grigorjeva (5):
      .......... [ZBXNEXT-686] added comment about timezone format update
      .......... [DEV-2237] fixed getting input type for macros
      .......... [DEV-2246] added new test for update problem popup
      .......... [ZBXNEXT-686] fixed time related tests
      .......... [ZBXNEXT-686] fixed triggers top report test

Michael Veksler (2):
      ...G...... [ZBX-21452] fixed wmi.get* crashes of zabbix_agentd
      .......PS. [ZBXNEXT-6401] added new vmware keys vmware.datastore.perfcounter and vmware.hv.diskinfo.get

Mihails Prihodko (5):
      .......... [DEV-2263] converted built-in postgresql plugin to standalone plugin
      .......... [DEV-2263] removed tlsconfig from agent2; updated go.mod for agent2
      .......... [DEV-2263] removed unused file left by mistake
      .......... [DEV-2263] removed unused dependencies gopkg.in/yaml.v2, github.com/stretchr/testify
      .......... [DEV-2263] updated plugin-support dependency

Natalja Romancaka (8):
      .......... [DEV-2210] added new test for dashboard properties form
      .......... [DEV-2210] removed trailing comma
      .......... [DEV-2184] removed commented lines, changed back item ids
      .......... [DEV-2184] changed back discovery id
      .......... [DEV-2184] added user to test from data source
      .......... [ZBXNEXT-686] fixed Selenium tests, added additional waits
      .......... [DEV-2257] added isEnabled for color picker element, removed TODO
      .......... [DEV-2067] fixed Selenium test, added filter for visible fields

Reinis Detlavs (4):
      ..F....... [DEV-2028] removed code related to displaying Standalone node name in enabled HA cluster
      ..F....... [DEV-2243] fixed Sql errors not logging in PHP error.log file using the MySQL database
      ..F....... [ZBX-21562] fixed maps not working with elements having disabled triggers
      ..F....... [ZBX-20505] fixed subfilter counters displaying incorrect values in Monitoring => Graph view

Roberts Lataria (1):
      A......... [ZBX-19224] added ability to unset headers in web scenario; conflict resolved: - ui/tests/selenium/testFormWeb.php

Sergejs Maklakovs (9):
      .......... [ZBXNEXT-826] updated release version [6.2.4rc1]; updated API version [6.2.4]
      .......... [DEV-2190] added new Audit log selenium autotest and API audit checks
      .......... [ZBXNEXT-686] fixed API audit autotests for 6.2
      .......... [ZBXNEXT-686] fixed API audit autotests deprecated value for 6.2
      .......... [ZBXNEXT-686] update autotests for 6.2
      .......... [ZBXNEXT-686] added static to 2 functions in CAPITest for 6.2
      .......... [ZBXNEXT-826] updated release date [6.2.4rc1]
      .......... [ZBXNEXT-826] updated changelog [6.2]
      .......... [ZBXNEXT-826] updated release date and version [6.2.4]

Sergejs Olonkins (8):
      .......... [DEV-1929] created autotest for Trigger overview widget
      .......... [DEV-1929] fixed minor issuevin 6.2 branch
      .......... [DEV-1929] added additional wait and fixed column selection in tests
      .......... [ZBXNEXT-686] fixed save method for Dashboard element
      .......... [ZBXNEXT-686] fixed name of the called method in autotest
      .......... [DEV-2067] resolved conflicts for SLA related tests task merge
      .......... [DEV-2067] fixed monthly and quarterly periods for last day of month
      .......... [ZBXNEXT-686] fixed reference time zone and SLA period calculations on first day of month

Tomass Olups (5):
      .......... [DEV-2184] updated autotests with the newest version of API source file
      .......... [DEV-2184] updated autotests for 6.2 branch
      .......... [DEV-2184] updated few autotests for 6.2 branch
      .......... [DEV-2184] updated testPageUserRoles autotest for 6.2 branch
      .......... [DEV-2184] updated data_test.sql in 6.2 branch

Vladislavs Sokurenko (5):
      ...G...... [ZBX-21227] fixed Zabbix agent to log received service control commands
      ........S. [ZBX-21537] fixed history syncers being stuck waiting on system information being collected
      ........S. [ZBX-21709] fixed database upgrade patch to skip unexpected invalid service downtime instead of failing
      .......PS. [ZBXNEXT-7970] added support of TimescaleDB 2.8
      .......PS. [ZBXNEXT-7816] added support of PostgreSQL 15

Vyacheslav Khaliev (18):
      .........T [ZBXNEXT-7902] added templates for Azure MySQL servers
      .........T [ZBXNEXT-7902] added graphs and fixed macros in Azure MySQL templates
      .........T [ZBXNEXT-7902] fixed resource name and keys in Azure MySQL templates
      .........T [ZBXNEXT-7902] fixed js in Azure template
      .........T [ZBXNEXT-7902] fixed discovery of MySQL servers in Azure template
      .........T [ZBXNEXT-7902] removed memory utilization trigger from Azure MySQL flexible server template
      .........T [ZBXNEXT-7902] fixed readme for Azure MySQL templates
      .........T [ZBXNEXT-7902] added triggers for failed connections in Azure MySQL templates
      .........T [ZBX-21581] optimized HPE Primera template to spread the load across preprocessing workers
      .........T [ZBX-21581] fixed HPE Primera template
      .........T [ZBX-21581] fixed preprocessing in HPE primera template
      .........T [ZBX-21582] optimized HPE Synergy template to spread the load across preprocessing workers
      .........T [ZBX-21582] fixed changelog file
      .........T [ZBXNEXT-7902] fixed threshold for aborted connections trigger in Azure Mysql templates
      .........T [ZBX-21582] fixed preprocessing and item key in HPE Synergy template
      .........T [ZBX-21582] updated HPE synergy template documentation
      .........T [ZBXNEXT-7902] fixed descriptions in Microsoft Azure templates
      .........T [ZBX-21673] fixed descriptions in Ceph by Zabbix agent 2 template